(package "searcher"
         "0.4.1"
         "Searcher in pure elisp")

(website-url "https://github.com/jcs-elpa/searcher")
(keywords "convenience" "search" "searcher" "string")

(package-file "searcher.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
